name: telethon-store
region: nyc
services:
  # Medusa Backend Service
  - name: medusa-backend
    source_dir: /telethon-store
    github:
      repo: MustacheTrashStash/telethon-store
      branch: main
      deploy_on_push: true
    run_command: yarn start
    build_command: yarn build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 9000
    health_check:
      http_path: /health
      port: 9000
    engines:
      node: "18.x"
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://doadmin:AVNS_8HuLDzB3YclMCGme9_o@medusa-db-do-user-3370563-0.e.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      - key: DATABASE_CA_CERT
        value: |
          -----BEGIN CERTIFICATE-----
          MIIEQTCCAqmgAwIBAgIUHVnx8LAYwLopZq1SPfizCkncdnwwDQYJKoZIhvcNAQEM
          BQAwOjE4MDYGA1UEAwwvMTY4NGYwODQtZGI1Mi00NTcyLWE1MjEtOTRlNzI0MDNl
          MTJlIFByb2plY3QgQ0EwHhcNMjMwMTE5MTcxNDU1WhcNMzMwMTE2MTcxNDU1WjA6
          MTgwNgYDVQQDDC8xNjg0ZjA4NC1kYjUyLTQ1NzItYTUyMS05NGU3MjQwM2UxMmUg
          UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAODbvLDe
          wQ0YWzWosJ6Z041C3tXtXQlIKwDyDXSm2XxUE45iv0AHdmc9rS/kFEVUbO/nYGNe
          RcTNBedNiCgh3S4zAOt+21S3NkBqglya3+DlS4IXfozYc6IQfbeU+rrn63jz4rpl
          y9ohRDIOmhUV6r45VqztzDYxg8Vp6MMYE5DZYPZW3Wws0CE968yO38ameZNlGol+
          mzyIOVreuAXwqZsqX6XerLGXIZw161EVg+1sH2yaM9lvn2xuZhufm93zDlwBRv+3
          8NxqowiOGtXIr0vfY4WyBprwEnN5egdrZkscfK7TIW7YtAMFJEW1DFvRdkTD8M1l
          OU58Oh3pfRkfaaCCcgL3YKI9Leur8B7GHpRomiqAXSPJYHqF/+HWfPWsbc/3+2kq
          kDR6BOoiBoKWZi5b3jgbfAEYWDSihI63C7s1FiltvlZuZULOCsAQ1hEBDnwlhVVS
          PcJBHM2T0OZrJw1lCr6ml83p9N8osc3VSxebYSFp5B8i1E2fZoLKYg7UQQIDAQAB
          oz8wPTAdBgNVHQ4EFgQU6ta6s18hZKQjrVeSEbqj7HoSYXIwDwYDVR0TBAgwBgEB
          /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBANOZ8Ggtj2LSfYSM
          ydJvhVlLO3hNGsATrg+dFULI9TuGc4i5sbdyqoQbZV3afdPLYbwfoa0VLRkVehNy
          ADmCb01LtcuWjTcAcuIc6//7OaXGh1bZUPvOCdB2j7qA99EG7p34IKZv1GokC5vn
          WBqg+lSieLs3ZxsgVqa+h8ta7LUDBAgpvH/R/KD/A9ETznsnroXCKlFgJPsUZ06l
          aBmQRStDJmbghuNFEfVHGCo71SE1o1xFxNypIb8hye+jVzYzywFoz8FwIuF2JaXJ
          WcQhsIm3N5PaEzuYm/U+CUJszQlvqou9Ob/yM1LfgGEc1YEjuL1RoHJ08HCB8Mjz
          RpT0Z2lNZHgdUvkIVvBrtO+Igx49ANfNK4y/h3S0UWa4/iCL8UEziP3EKEsXctZM
          nW4aZFmVkD3/a6SkB8lXoUxGjbwij0gbGGci39pqSOCupmXY5EWa41jh0ivX4gfo
          HhPNNj21DQZyY687vdt3HU9USPNtpD33O6ht6wFrKWrneMJQAw==
          -----END CERTIFICATE-----
      - key: JWT_SECRET
        value: your-super-secure-jwt-secret-change-this-in-production
      - key: COOKIE_SECRET
        value: your-super-secure-cookie-secret-change-this-in-production
      - key: STORE_CORS
        value: https://cctv.org/telethon,https://docs.medusajs.com
      - key: ADMIN_CORS
        value: https://cctv.org/telethon/admin,https://docs.medusajs.com
      - key: AUTH_CORS
        value: https://cctv.org/telethon,https://cctv.org/telethon/admin,https://docs.medusajs.com
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: nextjs
      - key: MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY
        value: telethon-store-storefront
      - key: DISABLE_ADMIN_BUILD
        value: "true"
      - key: MEDUSA_DISABLE_ADMIN
        value: "true"

  # Next.js Storefront Service
  - name: storefront
    source_dir: /telethon-store-storefront
    github:
      repo: MustacheTrashStash/telethon-store
      branch: main
      deploy_on_push: true
    run_command: yarn start
    build_command: yarn build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    health_check:
      http_path: /health
      port: 8000
    engines:
      node: "18.x"
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DEFAULT_REGION
        value: us
      - key: SKIP_BUILD_STATIC_GENERATION
        value: true
      - key: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
        value: pk_test_placeholder

# Database Migration Job
jobs:
  - name: migrate-db
    source_dir: /telethon-store
    github:
      repo: MustacheTrashStash/telethon-store
      branch: main
      deploy_on_push: true
    run_command: yarn medusa db:migrate
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    engines:
      node: "18.x"
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://doadmin:AVNS_8HuLDzB3YclMCGme9_o@medusa-db-do-user-3370563-0.e.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      - key: DATABASE_CA_CERT
        value: |
          -----BEGIN CERTIFICATE-----
          MIIEQTCCAqmgAwIBAgIUHVnx8LAYwLopZq1SPfizCkncdnwwDQYJKoZIhvcNAQEM
          BQAwOjE4MDYGA1UEAwwvMTY4NGYwODQtZGI1Mi00NTcyLWE1MjEtOTRlNzI0MDNl
          MTJlIFByb2plY3QgQ0EwHhcNMjMwMTE5MTcxNDU1WhcNMzMwMTE2MTcxNDU1WjA6
          MTgwNgYDVQQDDC8xNjg0ZjA4NC1kYjUyLTQ1NzItYTUyMS05NGU3MjQwM2UxMmUg
          UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAODbvLDe
          wQ0YWzWosJ6Z041C3tXtXQlIKwDyDXSm2XxUE45iv0AHdmc9rS/kFEVUbO/nYGNe
          RcTNBedNiCgh3S4zAOt+21S3NkBqglya3+DlS4IXfozYc6IQfbeU+rrn63jz4rpl
          y9ohRDIOmhUV6r45VqztzDYxg8Vp6MMYE5DZYPZW3Wws0CE968yO38ameZNlGol+
          mzyIOVreuAXwqZsqX6XerLGXIZw161EVg+1sH2yaM9lvn2xuZhufm93zDlwBRv+3
          8NxqowiOGtXIr0vfY4WyBprwEnN5egdrZkscfK7TIW7YtAMFJEW1DFvRdkTD8M1l
          OU58Oh3pfRkfaaCCcgL3YKI9Leur8B7GHpRomiqAXSPJYHqF/+HWfPWsbc/3+2kq
          kDR6BOoiBoKWZi5b3jgbfAEYWDSihI63C7s1FiltvlZuZULOCsAQ1hEBDnwlhVVS
          PcJBHM2T0OZrJw1lCr6ml83p9N8osc3VSxebYSFp5B8i1E2fZoLKYg7UQQIDAQAB
          oz8wPTAdBgNVHQ4EFgQU6ta6s18hZKQjrVeSEbqj7HoSYXIwDwYDVR0TBAgwBgEB
          /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBANOZ8Ggtj2LSfYSM
          ydJvhVlLO3hNGsATrg+dFULI9TuGc4i5sbdyqoQbZV3afdPLYbwfoa0VLRkVehNy
          ADmCb01LtcuWjTcAcuIc6//7OaXGh1bZUPvOCdB2j7qA99EG7p34IKZv1GokC5vn
          WBqg+lSieLs3ZxsgVqa+h8ta7LUDBAgpvH/R/KD/A9ETznsnroXCKlFgJPsUZ06l
          aBmQRStDJmbghuNFEfVHGCo71SE1o1xFxNypIb8hye+jVzYzywFoz8FwIuF2JaXJ
          WcQhsIm3N5PaEzuYm/U+CUJszQlvqou9Ob/yM1LfgGEc1YEjuL1RoHJ08HCB8Mjz
          RpT0Z2lNZHgdUvkIVvBrtO+Igx49ANfNK4y/h3S0UWa4/iCL8UEziP3EKEsXctZM
          nW4aZFmVkD3/a6SkB8lXoUxGjbwij0gbGGci39pqSOCupmXY5EWa41jh0ivX4gfo
          HhPNNj21DQZyY687vdt3HU9USPNtpD33O6ht6wFrKWrneMJQAw==
          -----END CERTIFICATE-----

# Database and Redis services
databases:
  - name: telethon-valkey
    engine: REDIS
    size: basic-xxs
    num_nodes: 1
    version: "7"
