name: telethon-store
region: nyc
services:
  # Medusa Backend Service
  - name: medusa-backend
    source_dir: /telethon-store
    github:
      repo: MustacheTrashStash/telethon-store
      branch: main
      deploy_on_push: true
    run_command: yarn run build-and-start
    # Remove the build_command line
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 9000
    health_check:
      http_path: /health
      port: 9000
    engines:
      node: "18.x"
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: COOKIE_SECRET
        value: ${COOKIE_SECRET}
      - key: STORE_CORS
        value: https://cctv.org/telethon,https://docs.medusajs.com
      - key: ADMIN_CORS
        value: https://cctv.org/telethon/admin,https://docs.medusajs.com
      - key: AUTH_CORS
        value: https://cctv.org/telethon,https://cctv.org/telethon/admin,https://docs.medusajs.com
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: nextjs
      - key: MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY
        value: telethon-store-storefront

  # Next.js Storefront Service
  - name: storefront
    source_dir: /telethon-store-storefront
    github:
      repo: MustacheTrashStash/telethon-store
      branch: main
      deploy_on_push: true
    run_command: yarn start
    build_command: yarn run build:full
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    health_check:
      http_path: /health
      port: 8000
    engines:
      node: "18.x"
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DEFAULT_REGION
        value: us
      - key: SKIP_BUILD_STATIC_GENERATION
        value: true
      - key: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
        value: pk_test_placeholder

# Database Migration Job
jobs:
  - name: migrate-db
    source_dir: /telethon-store
    github:
      repo: MustacheTrashStash/telethon-store
      branch: main
      deploy_on_push: true
    run_command: yarn medusa db:migrate
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    engines:
      node: "18.x"
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}

# Database and Redis services
databases:
  - name: telethon-valkey
    engine: REDIS
    size: basic-xxs
    num_nodes: 1
    version: "7"
